### PR TITLE
fix security warnings

### PR DESCRIPTION
**Pull request by ersel**
running `npm audit` returns 

```
found 7 vulnerabilities (2 low, 4 moderate, 1 critical) in 245 scanned packages
```

this PR resolves that. Both test suites are working.

### CODE REVIEW

**Comment by pchudzik** [comment]
This means that nodes version 0.12 and 4.x will no longer be supported.

I guess that's fine since they've reached their official end of life :)

I'll double check if other dependencies can be bumped more since support for older nodejs versions will be dropped. I'll also update travisci.yml file to exclude olde node versions. Then I'll release it as next version.

Thank you for this PR. I'll try to merge and release it later this week.

**Comment by ersel** [comment]
Thanks @pchudzik , we run `npm audit` as part of our CI process and this is the only warning left in there, would be nice to clean it up 👍

**Comment by pchudzik** [comment]
Published
https://www.npmjs.com/package/angular-template-cache/v/1.3.2

Thank you and have fun :)

**Comment by ersel** [comment]
thanks 👍

**Pull request merged**
